version: 2
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/gunfish/
    binary: gunfish
    ldflags:
      - -s -w
      - -X main.version=v{{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - name_template: "{{.ProjectName}}_v{{.Version}}_{{.Os}}_{{.Arch}}"

release:
  prerelease: "true"
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
