// generated by stringer -type Environment const.go; DO NOT EDIT

package gunfish

import "fmt"

const _Environment_name = "ProductionDevelopmentTestDisable"

var _Environment_index = [...]uint8{0, 10, 21, 25, 32}

func (i Environment) String() string {
	if i < 0 || i >= Environment(len(_Environment_index)-1) {
		return fmt.Sprintf("Environment(%d)", i)
	}
	return _Environment_name[_Environment_index[i]:_Environment_index[i+1]]
}
