// Code generated by "stringer -type ErrorResponseCode error.go"; DO NOT EDIT.

package apns

import "fmt"

const _ErrorResponseCode_name = "PayloadEmptyPayloadTooLargeBadTopicTopicDisallowedBadExpirationDateBadPriorityMissingDeviceTokenBadDeviceTokenDeviceTokenNotForTopicUnregisteredDuplicateHeadersBadCertificateEnvironmentBadCertificateForbiddenBadPathMethodNotAllowedTooManyRequestsIdleTimeoutShutdownInternalServerErrorServiceUnavailableMissingTopicBadCollapseIdBadMessageIdExpiredProviderTokenInvalidProviderTokenMissingProviderTokenTooManyProviderTokenUpdates"

var _ErrorResponseCode_index = [...]uint16{0, 12, 27, 35, 50, 67, 78, 96, 110, 132, 144, 160, 185, 199, 208, 215, 231, 246, 257, 265, 284, 302, 314, 327, 339, 359, 379, 399, 426}

func (i ErrorResponseCode) String() string {
	if i < 0 || i >= ErrorResponseCode(len(_ErrorResponseCode_index)-1) {
		return fmt.Sprintf("ErrorResponseCode(%d)", i)
	}
	return _ErrorResponseCode_name[_ErrorResponseCode_index[i]:_ErrorResponseCode_index[i+1]]
}
