// generated by stringer -type GCMErrorResponseCode error.go; DO NOT EDIT

package gcm

import "fmt"

const _GCMErrorResponseCode_name = "MissingRegistrationInvalidRegistrationNotRegisteredInvalidPackageNameMismatchSenderIdMessageTooBigInvalidDataKeyInvalidTtlDeviceMessageRateExceededTopicsMessageRateExceededInvalidApnsCredentialsAuthenticationErrorInvalidJSONUnavailableInternalServerErrorUnknownError"

var _GCMErrorResponseCode_index = [...]uint16{0, 19, 38, 51, 69, 85, 98, 112, 122, 147, 172, 194, 213, 224, 235, 254, 266}

func (i GCMErrorResponseCode) String() string {
	if i < 0 || i >= GCMErrorResponseCode(len(_GCMErrorResponseCode_index)-1) {
		return fmt.Sprintf("GCMErrorResponseCode(%d)", i)
	}
	return _GCMErrorResponseCode_name[_GCMErrorResponseCode_index[i]:_GCMErrorResponseCode_index[i+1]]
}
