name: Release
on:
  push:
    branches:
      - "!**/*"
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: fujiwara
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker
        run: |
          PATH=~/bin:$PATH make docker-push
