name: test
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go:
          - "1.21"
          - "1.20"
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Build & Test
        run: |
          make test
